### ISSUE TITLE
请教个关于“加载更多”的实现

### ISSUE THREAD

**Issue by lmule** [shenhualxt/JianDanIOS#1]
hi 你好，首先感谢您煎蛋的项目，让我学到不少东西
在我自己写“加载更多”这个功能的时候，viewmodel中是这么写的
self.signal = [RACSignal empty];
    self.dataSourceCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(RACTuple *tuple) {
        RACSignal *currentSignal = [LostDAO getLostInfoList:self.queryDict];
        self.signal = [self.signal merge:currentSignal];
        return self.signal;
    }];
currentSignal是下一页数据的signal，每次和当前的merge一下，但是在tableview的数据条数一直没变，一直只有第一页请求的数据数，但我每次点击下一页，有时候会渲染第二页的数据，有时候会渲染第三页的数据，没太看出来是啥原因，所以请教下，谢谢

**Comment by shenhualxt** [comment]
merge的用法

+merge: 前面在flatten中提到的水龙头的合并

RACSubject *letters = [RACSubject subject];
RACSubject *numbers = [RACSubject subject];
RACSignal *merged = [RACSignal merge:@[ letters, numbers ]];

// Outputs: A 1 B C 2
[merged subscribeNext:^(NSString *x) {
    NSLog(@"%@", x);
}];

[letters sendNext:@"A"];
[numbers sendNext:@"1"];
[letters sendNext:@"B"];
[letters sendNext:@"C"];
[numbers sendNext:@"2"];

参考：http://www.itiger.me/?p=38

分析：
//当第一次执行时
[dataSourceCommand execute:nil];
//    signal包含[RACSignal empty]（空的，订阅后不会做任何时）和currentSignal（订阅后请求第一页的数据）
//    所以[LostDAO getLostInfoList:self.queryDict]执行一次
//    所以一直只有第一页请求的数据数
//第二次执行 即点击下一页时
[dataSourceCommand execute:nil];
//    signal包含[RACSignal empty]（空的）和currentSignal（相当于第二页的数据）和currentSignal（相当于第三页的数据）(有merge了一次)
// 两次网络请求 快的会覆盖慢得
//所以会导致----有时候会渲染第二页的数据，有时候会渲染第三页的数据

**Comment by shenhualxt** [comment]
//修改如下
    RACSignal *signal = [RACSignal empty];
    RACCommand *dataSourceCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(RACTuple *tuple) {
        RACSignal *currentSignal = [LostDAO getLostInfoList:self.queryDict];
        signal = [signal merge:currentSignal];
        return [signal map:^id(NSArray *NextPageArray) {
            //记得初始化 self.dataSourceArray
            [self.dataSourceArray addObjectsFromArray:NextPageArray];
            return self.dataSourceArray;
        }];
    }];

```
//只要在加载下一页时调用
[[dataSourceCommand execute:@"这里是下一页的参数"];
```

//    即能实现列表下拉加载更多的功能

**Comment by shenhualxt** [comment]
去掉merge那一行

**Comment by shenhualxt** [comment]
```
RACCommand *dataSourceCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(RACTuple *tuple) {
    return  [[LostDAO getLostInfoList:self.queryDict] map:^id(NSArray *NextPageArray) {
        //记得初始化 self.dataSourceArray
        [self.dataSourceArray addObjectsFromArray:NextPageArray];
        return self.dataSourceArray;
    }];
}];
```

**Comment by lmule** [comment]
现在已经解决那个问题了，我看了下merge的源码，大概对机制理解了，谢谢您的提示和帮助
谢谢
